// <auto-generated />
using System;
using CrystalSharp.Tests.Common.PostgreSql.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrystalSharp.Tests.Common.Migrations.PostgreSqlMigrations
{
    [DbContext(typeof(PostgreSqlAppDbContext))]
    [Migration("20240207013733_PostgreSqlInitTestingDb")]
    partial class PostgreSqlInitTestingDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrystalSharp.Tests.Common.PostgreSql.Aggregates.DepartmentAggregate.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("GlobalUId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("CrystalSharp.Tests.Common.PostgreSql.Aggregates.DepartmentAggregate.Department", b =>
                {
                    b.OwnsOne("CrystalSharp.Tests.Common.PostgreSql.Aggregates.DepartmentAggregate.DepartmentInfo", "DepartmentInfo", b1 =>
                        {
                            b1.Property<int>("DepartmentId")
                                .HasColumnType("integer");

                            b1.Property<string>("Code")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.HasKey("DepartmentId");

                            b1.ToTable("Department");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.Navigation("DepartmentInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
