// <auto-generated />
using System;
using CrystalSharp.Tests.Common.Oracle.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CrystalSharp.Tests.Common.Migrations.OracleMigrations
{
    [DbContext(typeof(OracleAppDbContext))]
    [Migration("20231218212013_OracleInitTestingDb")]
    partial class OracleInitTestingDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CrystalSharp.Tests.Common.Oracle.Aggregates.EmployeeAggregate.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODE");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDON");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ENTITYSTATUS");

                    b.Property<Guid>("GlobalUId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("GLOBALUID");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("MODIFIEDON");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NAME");

                    b.Property<long>("Version")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.ToTable("EMPLOYEE", "SYSTEM");
                });
#pragma warning restore 612, 618
        }
    }
}
