// <auto-generated />
using System;
using CrystalSharp.Tests.Common.Oracle.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CrystalSharp.Tests.Common.Migrations.OracleMigrations
{
    [DbContext(typeof(OracleAppDbReadModelStoreContext))]
    [Migration("20251231230926_OracleReadModelStoreInitTestingDb")]
    partial class OracleReadModelStoreInitTestingDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrystalSharp.Tests.Common.Oracle.ReadModels.CustomerReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ENTITYSTATUS");

                    b.Property<Guid>("GlobalUId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("GLOBALUID");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("MODIFIEDON");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("CUSTOMER", "SYSTEM");
                });
#pragma warning restore 612, 618
        }
    }
}
