<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrystalSharp.EventStores.KurrentDb\CrystalSharp.EventStores.KurrentDb.csproj" />
    <ProjectReference Include="..\CrystalSharp.Messaging.AzureServiceBus\CrystalSharp.Messaging.AzureServiceBus.csproj" />
    <ProjectReference Include="..\CrystalSharp.Messaging.RabbitMq\CrystalSharp.Messaging.RabbitMq.csproj" />
    <ProjectReference Include="..\CrystalSharp.MsSql\CrystalSharp.MsSql.csproj" />
    <ProjectReference Include="..\CrystalSharp.MySql\CrystalSharp.MySql.csproj" />
    <ProjectReference Include="..\CrystalSharp.Oracle\CrystalSharp.Oracle.csproj" />
    <ProjectReference Include="..\CrystalSharp.PostgreSql\CrystalSharp.PostgreSql.csproj" />
    <ProjectReference Include="..\CrystalSharp\CrystalSharp.csproj" />
  </ItemGroup>

</Project>
